export const REGIONS  = [
  "Toshkent",
  "Andijon",
  "Buxoro",
  "Guliston",
  "Jizzax",
  "Navoiy",
  "Namangan",
  "Nukus",
  "Samarqand",
  "Termiz",
  "Urganch",
  "Fargona",
  "Qarshi",
  "Margilon",
  "Xiva",
  "Qoqon",
  "Angren",
  "Bekobod",
  "Denov",
  "Zomin",
  "Zarafshon",
  "Nurota",
  "Pop",
  "Urgut",
  "Xazorasp",
  "Chust",
  "Shahrixon",
  "Qorakol",
]

export const WEEKS = ['dushanba', 'seshanba', 'chorshanba', 'payshanba', 'juma', 'shanba','yakshanba']